words = [
    "SYLT",
    "USLT",
    "expander",
    "gresource",
    "gresources",
    "lrc",
    "lrclib",
    "lyricade",
    "ndt",
    "seekbar",
    "unsync",
]
ignore_patterns = ['".*\w.*_.*"']
