# Config for codebook spellchecker
words = [
    "expander",
    "gresource",
    "gresources",
    "lrc",
    "lrclib",
    "lyricade",
    "ndt",
    "unsync",
]

ignore_patterns = [
  # Ignore quoted words that include underscores that are
  # used to define relm4 access key mnemonics, e.g. "Simpl_e"
    '".*\w.*_.*"',
]
