words = [
    "Microlink",
    "SYLT",
    "Simp",
    "USLT",
    "azlyrics",
    "expander",
    "gresource",
    "gresources",
    "lrc",
    "lrclib",
    "lyricade",
    "ndt",
    "seekbar",
    "simpmusic",
    "unsync",
]
ignore_patterns = ['".*\w.*_.*"']
