name = "lyricade"
product-name = "Lyricade"
identifier = "io.github.weiteck.Lyricade"
version = "0.1.0"
description = "Download and manage lyrics for your music library"
authors = ["Chris Price <fair.lake5766_AT_fastmail.com>"]
copyright = "Copyright © 2026 Chris Price"
homepage = "https://github.com/weiteck/lyricade"
categories = ["AudioVideo", "Music"]

formats = ["appimage"]

before-packaging-command = "cargo build --release"

icons = [
    "data/icons/io.github.weiteck.Lyricade.svg"
]

[[binaries]]
path = "target/release/lyricade"
main = true

[appimage]
# This plugin instructs linuxdeploy to bundle the required GSettings schemas,
# pixbuf loaders, and core GTK assets so it can run on systems without GTK4 installed.
linuxdeploy-plugins = { gtk = "https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh" }
