name: Build & Package AppImage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-appimage:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libglib2.0-dev \
            libgtk-4-dev \
            libadwaita-1-dev \
            build-essential

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Install cargo-packager
        run: cargo install cargo-packager --locked

      - name: Build and Bundle AppImage
        env:
          DEPLOY_GTK_VERSION: 4
          NO_STRIP: "true"
          APPIMAGE_EXTRACT_AND_RUN: 1
        run: cargo packager --release --formats appimage -c Packager.toml

      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lyricade-appimage
          path: ./*.AppImage
